/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package webmapcreator;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Javier Garcia Garcia <javigarciavlc@gmail.com>
 */
public class NewJFrame extends javax.swing.JFrame {

    String zoom = "5";
    String posicion[] = {"60", "75", "20", "15"};  //Array para contener ancho largo y margenes
    String titulo = "";
    String marco[] = {"2", "Black"};
    String centromapa[] = {"-3.712", "40.423"};
    String controles[] = {"map.addControl( new OpenLayers.Control.LayerSwitcher() );", "map.addControl( new OpenLayers.Control.Scale() );", "map.addControl( new OpenLayers.Control.MousePosition() );", "map.addControl( new OpenLayers.Control.PanZoomBar() );", "map.addControl( new OpenLayers.Control.ScaleLine() );", "map.addControl( new OpenLayers.Control.OverviewMap() );"};
    Mapa m = new Mapa(zoom, posicion, titulo, marco, centromapa, controles);
    ArrayList<Integer> indicesselec = new ArrayList<Integer>();  //Variable que guarda los indices de las capas seleccionadas
    ArrayList<String> namesselec = new ArrayList<String>();  //Variable que guarda los nombres de las capas seleccionadas
    ArrayList<Integer> aux = new ArrayList<Integer>();

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        
        //Añadimos una capa  de iniciación a las capas del mapa
        indicesselec.add(0);
        namesselec.add("OpenStreetMap");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Color = new javax.swing.JColorChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Parametros = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        Crear = new javax.swing.JButton();
        Elegirzoom = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        longitud = new javax.swing.JTextField();
        latitud = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        Visualizacion = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Martop = new javax.swing.JSpinner();
        Ancho = new javax.swing.JSpinner();
        Marizq = new javax.swing.JSpinner();
        Largo = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        Titulo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Borde = new javax.swing.JCheckBox();
        Grosorborde = new javax.swing.JTextField();
        elegircolor = new javax.swing.JButton();
        Controles = new javax.swing.JDesktopPane();
        MiniMapa = new javax.swing.JCheckBox();
        Gestorcapas = new javax.swing.JCheckBox();
        Escalanumerica = new javax.swing.JCheckBox();
        Coordenadaspuntero1 = new javax.swing.JCheckBox();
        controlzoom = new javax.swing.JCheckBox();
        Escalagrafica = new javax.swing.JCheckBox();
        Controles1 = new javax.swing.JDesktopPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        capascargadas = new javax.swing.JList();
        bajarcapa = new javax.swing.JButton();
        añadircapa = new javax.swing.JButton();
        quitarcapa = new javax.swing.JButton();
        subircapa = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        capasdisponibles = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));

        Parametros.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Nivel de Zoom");
        jLabel1.setBounds(40, 30, 80, 14);
        Parametros.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Crear.setText("Crear Mapa");
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });
        Crear.setBounds(260, 230, 100, 23);
        Parametros.add(Crear, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Elegirzoom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        Elegirzoom.setSelectedIndex(4);
        Elegirzoom.setToolTipText("Nivel de zoom sobre el mapa");
        Elegirzoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElegirzoomActionPerformed(evt);
            }
        });
        Elegirzoom.setBounds(130, 29, 50, 20);
        Parametros.add(Elegirzoom, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setText("Centro del mapa");
        jLabel3.setBounds(39, 73, 100, 14);
        Parametros.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBounds(135, 53, 30, 60);
        Parametros.add(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setText("Longitud");
        jLabel8.setBounds(150, 60, 60, 14);
        Parametros.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel9.setText("Latitud");
        jLabel9.setBounds(150, 90, 50, 14);
        Parametros.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        longitud.setText("-3.7120");
        longitud.setToolTipText("Grosor del borde del mapa en pixeles");
        longitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                longitudActionPerformed(evt);
            }
        });
        longitud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                longitudKeyReleased(evt);
            }
        });
        longitud.setBounds(206, 56, 60, 25);
        Parametros.add(longitud, javax.swing.JLayeredPane.DEFAULT_LAYER);

        latitud.setText("40.4230");
        latitud.setToolTipText("Grosor del borde del mapa en pixeles");
        latitud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                latitudKeyReleased(evt);
            }
        });
        latitud.setBounds(206, 87, 60, 25);
        Parametros.add(latitud, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setBounds(30, 53, 30, 60);
        Parametros.add(jSeparator2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator3.setBounds(30, 110, 105, 2);
        Parametros.add(jSeparator3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator4.setBounds(30, 52, 105, 10);
        Parametros.add(jSeparator4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("Parametros", Parametros);

        Visualizacion.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("Largo");
        jLabel2.setBounds(40, 63, 40, 14);
        Visualizacion.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setText("Ancho");
        jLabel4.setBounds(40, 33, 50, 14);
        Visualizacion.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setText("Margen izquierdo");
        jLabel5.setBounds(40, 93, 90, 14);
        Visualizacion.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Martop.setModel(new javax.swing.SpinnerNumberModel(15, 0, 100, 1));
        Martop.setToolTipText("Porcentaje de pantalla de espacio que habrá encima del mapa");
        Martop.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                MartopStateChanged(evt);
            }
        });
        Martop.setBounds(160, 120, 50, 25);
        Visualizacion.add(Martop, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Ancho.setModel(new javax.swing.SpinnerNumberModel(60, 0, 100, 1));
        Ancho.setToolTipText("Porcentaje de la pantalla");
        Ancho.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                AnchoStateChanged(evt);
            }
        });
        Ancho.setBounds(160, 30, 50, 25);
        Visualizacion.add(Ancho, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Marizq.setModel(new javax.swing.SpinnerNumberModel(20, 0, 100, 1));
        Marizq.setToolTipText("Porcentaje de pantalla de espacio que habrá a la izquierda del mapa");
        Marizq.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                MarizqStateChanged(evt);
            }
        });
        Marizq.setBounds(160, 90, 50, 25);
        Visualizacion.add(Marizq, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Largo.setModel(new javax.swing.SpinnerNumberModel(75, 0, 100, 1));
        Largo.setToolTipText("Porcentaje de la pantalla");
        Largo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                LargoStateChanged(evt);
            }
        });
        Largo.setBounds(160, 60, 50, 25);
        Visualizacion.add(Largo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setText("Margen de arriba");
        jLabel6.setBounds(40, 123, 90, 14);
        Visualizacion.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Titulo.setToolTipText("Titulo de la pestaña del navegador");
        Titulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TituloKeyReleased(evt);
            }
        });
        Titulo.setBounds(160, 150, 100, 25);
        Visualizacion.add(Titulo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setText("Titulo");
        jLabel7.setBounds(40, 154, 60, 14);
        Visualizacion.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Borde.setSelected(true);
        Borde.setText("Borde");
        Borde.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                BordeItemStateChanged(evt);
            }
        });
        Borde.setBounds(40, 182, 90, 23);
        Visualizacion.add(Borde, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Grosorborde.setText("2");
        Grosorborde.setToolTipText("Grosor del borde del mapa en pixeles");
        Grosorborde.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                GrosorbordeKeyReleased(evt);
            }
        });
        Grosorborde.setBounds(160, 180, 50, 25);
        Visualizacion.add(Grosorborde, javax.swing.JLayeredPane.DEFAULT_LAYER);

        elegircolor.setText("Color");
        elegircolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elegircolorActionPerformed(evt);
            }
        });
        elegircolor.setBounds(230, 182, 70, 23);
        Visualizacion.add(elegircolor, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("Visualizacion", Visualizacion);

        Controles.setBackground(new java.awt.Color(204, 204, 204));

        MiniMapa.setSelected(true);
        MiniMapa.setText("MiniMapa");
        MiniMapa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MiniMapaItemStateChanged(evt);
            }
        });
        MiniMapa.setBounds(40, 180, 170, 23);
        Controles.add(MiniMapa, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Gestorcapas.setSelected(true);
        Gestorcapas.setLabel("Gestor de capas");
        Gestorcapas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                GestorcapasItemStateChanged(evt);
            }
        });
        Gestorcapas.setBounds(40, 30, 170, 23);
        Controles.add(Gestorcapas, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Escalanumerica.setSelected(true);
        Escalanumerica.setText("Escala numerica");
        Escalanumerica.setActionCommand("escala");
        Escalanumerica.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                EscalanumericaItemStateChanged(evt);
            }
        });
        Escalanumerica.setBounds(40, 60, 170, 23);
        Controles.add(Escalanumerica, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escalanumerica.getAccessibleContext().setAccessibleName("Escala");

        Coordenadaspuntero1.setSelected(true);
        Coordenadaspuntero1.setLabel("Coordenadas del puntero");
        Coordenadaspuntero1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Coordenadaspuntero1ItemStateChanged(evt);
            }
        });
        Coordenadaspuntero1.setBounds(40, 150, 170, 23);
        Controles.add(Coordenadaspuntero1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        controlzoom.setSelected(true);
        controlzoom.setText("Control de zoom");
        controlzoom.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                controlzoomItemStateChanged(evt);
            }
        });
        controlzoom.setBounds(40, 120, 170, 23);
        Controles.add(controlzoom, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Escalagrafica.setSelected(true);
        Escalagrafica.setText("Escala grafica");
        Escalagrafica.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                EscalagraficaItemStateChanged(evt);
            }
        });
        Escalagrafica.setBounds(40, 90, 170, 23);
        Controles.add(Escalagrafica, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("Controles", Controles);

        Controles1.setBackground(new java.awt.Color(204, 204, 204));

        capascargadas.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "OpenStreetMap" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        capascargadas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(capascargadas);

        jScrollPane2.setBounds(240, 50, 140, 200);
        Controles1.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        bajarcapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/webmapcreator/imagenes/Flechaabajo.png"))); // NOI18N
        bajarcapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajarcapaActionPerformed(evt);
            }
        });
        bajarcapa.setBounds(180, 200, 40, 30);
        Controles1.add(bajarcapa, javax.swing.JLayeredPane.DEFAULT_LAYER);

        añadircapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/webmapcreator/imagenes/Flechaderecha.png"))); // NOI18N
        añadircapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadircapaActionPerformed(evt);
            }
        });
        añadircapa.setBounds(180, 80, 40, 30);
        Controles1.add(añadircapa, javax.swing.JLayeredPane.DEFAULT_LAYER);

        quitarcapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/webmapcreator/imagenes/Flechaizquierda.png"))); // NOI18N
        quitarcapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitarcapaActionPerformed(evt);
            }
        });
        quitarcapa.setBounds(180, 120, 40, 30);
        Controles1.add(quitarcapa, javax.swing.JLayeredPane.DEFAULT_LAYER);

        subircapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/webmapcreator/imagenes/Flechaarriba.png"))); // NOI18N
        subircapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subircapaActionPerformed(evt);
            }
        });
        subircapa.setBounds(180, 160, 40, 30);
        Controles1.add(subircapa, javax.swing.JLayeredPane.DEFAULT_LAYER);

        capasdisponibles.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "OpenStreetMap", "OpenStreetMap Toner", "OSM MapQuest", "OSM Ciclismo", "OSM Transporte", "OSM Humanitarian", "OSM Color de agua", "Google Fisico", "Google Streets", "Google Hibrido", "Google Satelite", "Bing Carreteras", "Bing Aereo", "Bing Aereo con etiquetas", "OpenGeo Global", "OpenGeo Azul", "OpenGeo Tiza", "OpenGeo Grafito", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(capasdisponibles);

        jScrollPane3.setBounds(20, 50, 140, 200);
        Controles1.add(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("Capas", Controles1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
        m.setcapas(namesselec);
        m.Obtenerfichero();
    }//GEN-LAST:event_CrearActionPerformed

    private void ElegirzoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElegirzoomActionPerformed
        zoom = Elegirzoom.getSelectedItem().toString();
        m.setzoom(zoom);
        //JOptionPane.showMessageDialog(null, zoom, "ERROR", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_ElegirzoomActionPerformed

    private void AnchoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_AnchoStateChanged
        String ancho = Ancho.getValue().toString();
        posicion[0] = ancho;
        m.setposicion(posicion);
    }//GEN-LAST:event_AnchoStateChanged

    private void LargoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_LargoStateChanged
        String largo = Largo.getValue().toString();
        posicion[1] = largo;
        m.setposicion(posicion);
    }//GEN-LAST:event_LargoStateChanged

    private void MarizqStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_MarizqStateChanged
        String marizq = Marizq.getValue().toString();
        posicion[2] = marizq;
        m.setposicion(posicion);
    }//GEN-LAST:event_MarizqStateChanged

    private void MartopStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_MartopStateChanged
        String martop = Martop.getValue().toString();
        posicion[3] = martop;
        m.setposicion(posicion);
    }//GEN-LAST:event_MartopStateChanged

    private void TituloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TituloKeyReleased
        titulo = Titulo.getText();
        m.settitulo(titulo);
    }//GEN-LAST:event_TituloKeyReleased

    private void BordeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_BordeItemStateChanged

        if (Borde.isSelected() == true) {

            Grosorborde.setEnabled(true);
            elegircolor.setEnabled(true);
            m.setgrosor(marco[0]);
            Grosorborde.setText(marco[0]);

        } else {

            Grosorborde.setEnabled(false);
            elegircolor.setEnabled(false);
            m.setgrosor("0");
            Grosorborde.setText(marco[0]);

        }
    }//GEN-LAST:event_BordeItemStateChanged

    private void GrosorbordeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GrosorbordeKeyReleased
        marco[0] = Grosorborde.getText();
        m.setgrosor(marco[0]);
    }//GEN-LAST:event_GrosorbordeKeyReleased

    private void elegircolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elegircolorActionPerformed

        Color color = Color.showDialog(rootPane, titulo, Color.getColor());
        String rgb = Integer.toHexString(color.getRGB());
        rgb = rgb.substring(2, rgb.length()); //Le quitamos los dos primeros digitos al color
        marco[1] = "#" + rgb;
        m.setcolor(marco[1]);
    }//GEN-LAST:event_elegircolorActionPerformed

    private void longitudKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_longitudKeyReleased
        centromapa[0] = longitud.getText();
        m.setcentromapa(centromapa);
    }//GEN-LAST:event_longitudKeyReleased

    private void latitudKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_latitudKeyReleased
        centromapa[1] = latitud.getText();
        m.setcentromapa(centromapa);
    }//GEN-LAST:event_latitudKeyReleased

    private void GestorcapasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_GestorcapasItemStateChanged

        if (Gestorcapas.isSelected() == true) {

            controles[0] = "map.addControl( new OpenLayers.Control.LayerSwitcher() );";

        } else {

            controles[0] = "";
        }

        m.setcontroles(controles);

    }//GEN-LAST:event_GestorcapasItemStateChanged

    private void EscalanumericaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_EscalanumericaItemStateChanged

        if (Escalanumerica.isSelected() == true) {

            controles[1] = "map.addControl( new OpenLayers.Control.Scale() );";

        } else {

            controles[1] = "";
        }

        m.setcontroles(controles);

    }//GEN-LAST:event_EscalanumericaItemStateChanged

    private void Coordenadaspuntero1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Coordenadaspuntero1ItemStateChanged


        if (Coordenadaspuntero1.isSelected() == true) {

            controles[2] = "map.addControl( new OpenLayers.Control.MousePosition() );";

        } else {

            controles[2] = "";
        }

        m.setcontroles(controles);

    }//GEN-LAST:event_Coordenadaspuntero1ItemStateChanged

    private void controlzoomItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_controlzoomItemStateChanged

        if (controlzoom.isSelected() == true) {

            controles[3] = "map.addControl( new OpenLayers.Control.PanZoomBar() );";

        } else {

            controles[3] = "";
        }

        m.setcontroles(controles);


    }//GEN-LAST:event_controlzoomItemStateChanged

    private void EscalagraficaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_EscalagraficaItemStateChanged


        if (Escalagrafica.isSelected() == true) {

            controles[4] = "map.addControl( new OpenLayers.Control.ScaleLine() );";

        } else {

            controles[4] = "";
        }

        m.setcontroles(controles);


    }//GEN-LAST:event_EscalagraficaItemStateChanged

    private void MiniMapaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MiniMapaItemStateChanged


        if (MiniMapa.isSelected() == true) {

            controles[5] = "map.addControl( new OpenLayers.Control.OverviewMap() );";

        } else {

            controles[5] = "";
        }

        m.setcontroles(controles);


    }//GEN-LAST:event_MiniMapaItemStateChanged

    private void añadircapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadircapaActionPerformed

        // Object[] seleccion = capasdisponibles.getSelectedValues();
        // capascargadas.setListData(seleccion);
        int[] indices = capasdisponibles.getSelectedIndices();
        Object[] seleccionname = capasdisponibles.getSelectedValues();


        for (int i = 0; i < indices.length; i++) {

            if (indicesselec.contains(indices[i])) {
            } else {
                indicesselec.add(indices[i]);
                namesselec.add(seleccionname[i].toString());
            }
        };

        Object[] seleccionnames = namesselec.toArray(new Object[namesselec.size()]);
        capascargadas.setListData(seleccionnames);

        //JOptionPane.showMessageDialog(null, seleccionname2[0], "ERROR", JOptionPane.WARNING_MESSAGE);

        //http://javapiola.blogspot.com.es/2009/11/como-utilizar-jlist-en-java.html
        //http://docs.oracle.com/javase/tutorial/uiswing/components/list.html

    }//GEN-LAST:event_añadircapaActionPerformed

    private void quitarcapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitarcapaActionPerformed

        int[] removeindices = capascargadas.getSelectedIndices();
        Object[] removeseleccionname = capascargadas.getSelectedValues();


        for (int i = 0; i < removeindices.length; i++) {

            indicesselec.remove(removeindices[i]);
            namesselec.remove(removeseleccionname[i]);
        };

        Object[] seleccionnames = namesselec.toArray(new Object[namesselec.size()]);
        capascargadas.setListData(seleccionnames);

    }//GEN-LAST:event_quitarcapaActionPerformed

    private void subircapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subircapaActionPerformed

        int orderindices = capascargadas.getSelectedIndex();

        if (orderindices != 0) {

            String actual = (String) capascargadas.getSelectedValue();
            String last = namesselec.get(orderindices - 1);

            namesselec.set((orderindices - 1), actual);
            namesselec.set((orderindices), last);

            Object[] seleccionnames = namesselec.toArray(new Object[namesselec.size()]);
            capascargadas.setListData(seleccionnames);
        }

    }//GEN-LAST:event_subircapaActionPerformed

    private void bajarcapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajarcapaActionPerformed

        int orderindices = capascargadas.getSelectedIndex();

        if (orderindices != (namesselec.size() - 1)) {

            String actual = (String) capascargadas.getSelectedValue();
            String next = namesselec.get(orderindices + 1);

            namesselec.set((orderindices + 1), actual);
            namesselec.set((orderindices), next);

            Object[] seleccionnames = namesselec.toArray(new Object[namesselec.size()]);
            capascargadas.setListData(seleccionnames);

        }

    }//GEN-LAST:event_bajarcapaActionPerformed

    private void longitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_longitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_longitudActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Ancho;
    private javax.swing.JCheckBox Borde;
    private javax.swing.JColorChooser Color;
    private javax.swing.JDesktopPane Controles;
    private javax.swing.JDesktopPane Controles1;
    private javax.swing.JCheckBox Coordenadaspuntero1;
    private javax.swing.JButton Crear;
    private javax.swing.JComboBox Elegirzoom;
    private javax.swing.JCheckBox Escalagrafica;
    private javax.swing.JCheckBox Escalanumerica;
    private javax.swing.JCheckBox Gestorcapas;
    private javax.swing.JTextField Grosorborde;
    private javax.swing.JSpinner Largo;
    private javax.swing.JSpinner Marizq;
    private javax.swing.JSpinner Martop;
    private javax.swing.JCheckBox MiniMapa;
    private javax.swing.JDesktopPane Parametros;
    private javax.swing.JTextField Titulo;
    private javax.swing.JDesktopPane Visualizacion;
    private javax.swing.JButton añadircapa;
    private javax.swing.JButton bajarcapa;
    private javax.swing.JList capascargadas;
    private javax.swing.JList capasdisponibles;
    private javax.swing.JCheckBox controlzoom;
    private javax.swing.JButton elegircolor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField latitud;
    private javax.swing.JTextField longitud;
    private javax.swing.JButton quitarcapa;
    private javax.swing.JButton subircapa;
    // End of variables declaration//GEN-END:variables
}
